[conda]
channel = "github-releases"

[[packages]]
repository = "axodotdev/cargo-dist"

[[packages]]
repository = "blopker/codebook"
name = "codebook-lsp"

[[packages]]
repository = "cargo-bins/cargo-binstall"

[[packages]]
repository = "cargo-generate/cargo-generate"

[[packages]]
repository = "crate-ci/cargo-release"

[[packages]]
repository = "davidlattimore/wild"

[[packages]]
repository = "est31/cargo-udeps"

[[packages]]
repository = "idursun/jjui"

[[packages]]
repository = "ifd3f/caligula"

[[packages]]
repository = "j178/prek"

[[packages]]
repository = "MathiasPius/crates-lsp"

[[packages]]
repository = "obi1kenobi/cargo-semver-checks"

[[packages]]
repository = "probe-rs/probe-rs"
name = "probe-rs-tools"

[[packages]]
repository = "rust-fuzz/cargo-fuzz"

[[packages]]
repository = "rvben/rumdl"

[[packages]]
repository = "xd009642/tarpaulin"

[[packages]]
repository = "Michael-F-Bryan/mdbook-linkcheck"
