[conda]
channel = "github-releases"

[[packages]]
repository = "ajeetdsouza/zoxide"

[[packages]]
repository = "ast-grep/ast-grep"

[[packages]]
repository = "atuinsh/atuin"

[[packages]]
repository = "axodotdev/cargo-dist"

[[packages]]
repository = "bergercookie/asm-lsp"

# ### TODO: Strange release tag names
# [[packages]]
# repository = "biomejs/biome"

[[packages]]
repository = "blopker/codebook"
name = "codebook-lsp"

[[packages]]
repository = "BurntSushi/ripgrep"

[[packages]]
repository = "cargo-bins/cargo-binstall"

[[packages]]
repository = "cargo-generate/cargo-generate"

[[packages]]
repository = "casey/just"

[[packages]]
repository = "ClementTsang/bottom"

[[packages]]
repository = "crate-ci/cargo-release"

[[packages]]
repository = "dandavison/delta"

[[packages]]
repository = "davidlattimore/wild"

[[packages]]
repository = "est31/cargo-udeps"

[[packages]]
repository = "eza-community/eza"

[[packages]]
repository = "idursun/jjui"

[[packages]]
repository = "ifd3f/caligula"

[[packages]]
repository = "jj-vcs/jj"

[[packages]]
repository = "j178/prek"

[[packages]]
repository = "MathiasPius/crates-lsp"

[[packages]]
repository = "Michael-F-Bryan/mdbook-linkcheck"

[[packages]]
repository = "neocmakelsp/neocmakelsp"

[[packages]]
repository = "neovim/neovim"

[[packages]]
repository = "obi1kenobi/cargo-semver-checks"

[[packages]]
repository = "probe-rs/probe-rs"
name = "probe-rs-tools"

[[packages]]
repository = "rgwood/systemctl-tui"

[[packages]]
repository = "rhysd/actionlint"

[[packages]]
repository = "rui314/mold"

[[packages]]
repository = "rust-fuzz/cargo-fuzz"

[[packages]]
repository = "rvben/rumdl"

[[packages]]
repository = "sharkdp/bat"

[[packages]]
repository = "sharkdp/hyperfine"

[[packages]]
repository = "starship/starship"

[[packages]]
repository = "tree-sitter/tree-sitter"
name = "tree-sitter"

[[packages]]
repository = "Wilfred/difftastic"

[[packages]]
repository = "xd009642/tarpaulin"

[[packages]]
repository = "YS-L/flamelens"

[[packages]]
repository = "zellij-org/zellij"

[[packages]]
repository = "zizmorcore/zizmor"
