[workspace]
authors = ["Tobias Hunger <tobias.hunger@gmail.com>"]
channels = ["conda-forge"]
name = "octoconda"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
actionlint = "*"
zizmor = "*"
rattler-build = "*"
