[conda]
channel = "https://prefix.dev/conda-forge"

# [[packages]]
# name = "test"
# repository = "foo/bar"

# [[packages]]
# repository = "jdx/mise"
# platforms = { "linux-64" = "linux-x64-musl.tar.xz", "linux-aarch64" = "linux-arm64-musl.tar.xz", "osx-64" = "macos-x64.tar.xz", "osx-arm64" = "macos-arm64.tar.xz", "win-arm64" = "windows-arm64.zip", "win-64" = "windows-x64.zip" }

# [[packages]]
# repository = "tukanni-project/xz"
[[packages]]
repository = "BurntSushi/ripgrep"

[packages.platforms]
linux-aarch64 = "-aarch64-unknown-linux-gnu.tar.gz$"
osx-arm64 = "-aarch64-apple-darwin.tar.gz$"
win-arm64 = "-aarch64-pc-windows-msvc.zip$"
linux-32 = "-i686-unknown-linux-gnu.tar.gz$"
linux-64 = "-x86_64-unknown-linux-musl.tar.gz$"
osx-64 = "-x86_64-apple-darwin.tar.gz$"
win-64 = "-x86_64-pc-windows-msvc.zip$"

